import fs from "node:fs";
import path from "node:path";
import type { Command } from "commander";
import { confirm, log } from "../output";
import { requireIndex } from "../store";
import type { SkillEntry } from "../types";
import { AbortedError, run } from "./common";

function skillLink(entry: SkillEntry): string {
  const repo = entry.repository.replace(/\/+$/, "");
  if (!/^https?:\/\//.test(repo)) return "";
  return entry.path === "" ? repo : `${repo}/tree/HEAD/${entry.path}`;
}

function escapeMarkdown(text: string): string {
  return text.replace(/\s+/g, " ").replace(/([*_`[\]])/g, "\\$1").trim();
}

function anchor(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-");
}

export function renderAwesomeList(index: SkillEntry[], generatedAt: string): string {
  const categories = new Map<string, SkillEntry[]>();
  for (const entry of index) {
    const group = categories.get(entry.category) ?? [];
    group.push(entry);
    categories.set(entry.category, group);
  }
  const sortedCategories = [...categories.keys()].sort((a, b) => a.localeCompare(b));
  const sources = new Map<string, SkillEntry>();
  for (const entry of index) if (!sources.has(entry.source)) sources.set(entry.source, entry);

  const lines: string[] = [];
  lines.push("# Awesome Community Agent Skills");
  lines.push("");
  lines.push(`A curated catalog of ${index.length} Agent Skills aggregated from ${sources.size} community repositories.`);
  lines.push(`Generated by ai-community-skills on ${generatedAt}. Risk levels come from static analysis only and are a starting point for review, not a guarantee.`);
  lines.push("");
  lines.push("## Contents");
  lines.push("");
  for (const category of sortedCategories) {
    lines.push(`- [${category}](#${anchor(category)}) (${categories.get(category)!.length})`);
  }
  lines.push("- [Sources](#sources)");
  lines.push("");
  for (const category of sortedCategories) {
    lines.push(`## ${category}`);
    lines.push("");
    const entries = [...categories.get(category)!].sort((a, b) => a.name.localeCompare(b.name) || a.source.localeCompare(b.source));
    for (const entry of entries) {
      const link = skillLink(entry);
      const title = link ? `[${entry.name}](${link})` : entry.name;
      const flags: string[] = [];
      if (entry.hasScripts) flags.push("scripts");
      if (entry.networkCalls) flags.push("network");
      if (entry.destructiveOps) flags.push(entry.confirmsBeforeDestructive ? "destructive with confirmation" : "destructive");
      if (entry.claudeCodeOnly) flags.push("claude-code only");
      const suffix = flags.length > 0 ? `, ${flags.join(", ")}` : "";
      lines.push(`- ${title} - ${escapeMarkdown(entry.description)} (source: ${entry.source}, risk: ${entry.riskLevel}${suffix})`);
    }
    lines.push("");
  }
  lines.push("## Sources");
  lines.push("");
  for (const [name, entry] of [...sources.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    const count = index.filter((item) => item.source === name).length;
    const stars = entry.sourceReputation.stars > 0 ? `, ${entry.sourceReputation.stars} stars` : "";
    lines.push(`- [${name}](${entry.repository}) - ${count} skills${stars}${entry.sourceReputation.hasCi ? ", CI configured" : ""}`);
  }
  lines.push("");
  return lines.join("\n");
}

export function registerExportAwesomeList(program: Command): void {
  program
    .command("export-awesome-list")
    .description("Generate an awesome-list.md from the full catalog")
    .option("--output <file>", "output file path", "awesome-list.md")
    .option("--yes", "overwrite an existing file without asking", false)
    .option("--dry-run", "print the markdown to stdout instead of writing a file", false)
    .action(
      run(async (options: { output: string; yes: boolean; dryRun: boolean }) => {
        const markdown = renderAwesomeList(requireIndex(), new Date().toISOString().slice(0, 10));
        if (options.dryRun) {
          process.stdout.write(markdown);
          return;
        }
        const target = path.resolve(options.output);
        if (fs.existsSync(target) && !options.yes) {
          const accepted = await confirm(`${target} already exists. Overwrite it?`);
          if (!accepted) throw new AbortedError("Export aborted.");
        }
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, markdown);
        log(`Wrote ${target}.`);
      }),
    );
}
